---@diagnostic disable: lowercase-global

function DoNothing()
      --Do absolutely nothing, and like it.
end

MarkGameStarted = function() bj_gameStarted = true end
InitGlobals = DoNothing --this is always found at the top of the map script, even when there are no udg_ globals

function GetBJMaxPlayerSlots()
    return 0
end
IngameConsole = false

require 'Debug Utils v2a'

require 'Total Initialization'

OnInit.root(function()
    print "1. This is called immediately"
end)
OnInit.config(function()
    print "2. This is called during the map config process (in game lobby)"
end)
OnInit.main(function()
    print "3. This is called during the loading screen"
end)
OnInit(function()
    print "4. All udg_ variables have been initialized"
end)
OnInit.trig(function()
    print "5. All InitTrig_ functions have been called"
end)
OnInit.map(function()
    print "6. All Map Initialization events have run"
end)
OnInit.final(function()
    print "7. The game has now started"
end)



OnInit("Yuna", function(needs)
    print("Yuna has arrived, thanks to Tidus, who is:",needs "Tidus")
    print("Yuna only optionally needs Kimhari, who is:",needs.optionally "Kimahri")
end)

OnInit("Tidus", function(requires)
    print("Tidus has loaded, thanks to Jecht, who is:", requires "Jecht")

    print "Tidus is declaring Rikku and yielding for initializers that need her."
    OnInit "Rikku"

    return "The Star Player of the Zanarkand Abes"
end)

OnInit("Cid", function(needs)
    print("Cid has arrived, thanks to Rikku, who is:",needs "Rikku")
end)

OnInit(function(uses)
    print("TEST FAILURE! Spira does not exist, so this should never be called.", uses "Spira")
end)

OnInit("Jecht", function(needs)
    print("Jecht requires Blitzball, which is:",needs"Blitzball")
    print("Jecht has arrived, without Sin, who is:",needs.readyOrNot "Sin")

    return "A Retired Blitzball Player", "An Alcoholic", "A bad father to Tidus"
end)

OnInit("Wakka", function(needs)
    print("Wakka requires Blitzball, which is:",needs"Blitzball")
    print("Wakka optionally requires Lulu, who is:", needs.ifHeFeelsLikeIt "Lulu")
end)

OnInit("Lulu", function(needs)
    print("Lulu optionally requires Wakka, who is:", needs.ifSheFeelsLikeIt "Wakka")
end)

OnInit("Blitzball", function()
    print "Blitzball has no requirements."
    return "Round", "Popular", "Extremely Dangerous"
end)

OnInit("Bevel", function(import)
    print("Bevel will not wait for Zanarkand, which is:", import.sleepily "Zanarkand")
end)

OnInit.trig("Ronso Fangs", function()
    print "The Ronso Fangs run last, because they are late bloomers."
end)

-- (write your own unit tests here) --


-- auto-generated functions like "CreateAllUnits" are placed here --


-- map header script is placed here --


-- GUI triggers are placed here --


-- this marks the end of the user's access to the Lua root, everything is auto-generated by World Editor beyond this point --


InitCustomTriggers = DoNothing
RunInitializationTriggers = DoNothing

print 'creating main'
function main()
    print 'calling InitGlobals'
    InitGlobals()
    
    print 'calling InitCustomTriggers'
    
    InitCustomTriggers()
    
    print 'calling RunInitializationTriggers'
    RunInitializationTriggers()
end

print 'creating config'
config = DoNothing

-- end of Lua root --

print 'calling config'
config() --called during the game lobby menu/prior to the game's loading screen.

print 'calling main'
main() --called first during the map loading screen.

print 'calling MarkGameStarted'

MarkGameStarted() --synthesize that the game has loaded.
